repos:
  - repo: https://github.com/mharrisb1/markings
    rev: v0.3.0
    hooks:
      - id: markings
        types: [text]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: trailing-whitespace
